// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkcIRWElnhcUoZbZ8kSFXC8SO8b19frpU',
    appId: '1:68537559030:web:38dbffcd873b92525909d7',
    messagingSenderId: '68537559030',
    projectId: 'rickandmorty-7c8b9',
    authDomain: 'rickandmorty-7c8b9.firebaseapp.com',
    storageBucket: 'rickandmorty-7c8b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDraQ-MeQZPNAv7c1w3hTdAEo0Kavs9cNE',
    appId: '1:68537559030:android:190008d067a96bb15909d7',
    messagingSenderId: '68537559030',
    projectId: 'rickandmorty-7c8b9',
    storageBucket: 'rickandmorty-7c8b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwTnZokTf-hnJijypFrKNlKj1TGS2uSSo',
    appId: '1:68537559030:ios:ea73502c89a4fbfe5909d7',
    messagingSenderId: '68537559030',
    projectId: 'rickandmorty-7c8b9',
    storageBucket: 'rickandmorty-7c8b9.appspot.com',
    iosBundleId: 'com.example.rickAndMorty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwTnZokTf-hnJijypFrKNlKj1TGS2uSSo',
    appId: '1:68537559030:ios:ea73502c89a4fbfe5909d7',
    messagingSenderId: '68537559030',
    projectId: 'rickandmorty-7c8b9',
    storageBucket: 'rickandmorty-7c8b9.appspot.com',
    iosBundleId: 'com.example.rickAndMorty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkcIRWElnhcUoZbZ8kSFXC8SO8b19frpU',
    appId: '1:68537559030:web:8a4ae6b5e32d2a5b5909d7',
    messagingSenderId: '68537559030',
    projectId: 'rickandmorty-7c8b9',
    authDomain: 'rickandmorty-7c8b9.firebaseapp.com',
    storageBucket: 'rickandmorty-7c8b9.appspot.com',
  );
}
